apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: {{ENVIRONMENT}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: {{IMAGE}}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
             # valueFrom:
              #  configMapKeyRef:
               #   name: app-config
                #  key: REDIS_HOST
              value: redis
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENVIRONMENT
