apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 445567093417.dkr.ecr.us-east-1.amazonaws.com/my-image
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "{{REDIS_HOST}}"
        - name: ENVIRONMENT
          value: "{{ENVIRONMENT}}"
