---
- name: Deploy and run Terraform on EC2
  hosts: ec2
  become: yes
  tasks:
    - name: Create working directory
      file:
        path: /home/ubuntu/terraform
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy all Terraform files to EC2
      copy:
        src: /home/mahmoud/final_project_konecta/Konecta_Final_Task/terraform/eks
        dest: /home/ubuntu/terraform/
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Install required dependencies (curl, unzip)
      apt:
        name:
          - curl
          - unzip
        state: present
        update_cache: yes

    - name: Install Terraform
      shell: |
        curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        mv terraform /usr/local/bin/
        rm terraform.zip
      args:
        creates: /usr/local/bin/terraform

    - name: Initialize Terraform
      become_user: ubuntu
      command: terraform init
      args:
        chdir: /home/ubuntu/terraform

    - name: Apply Terraform
      become_user: ubuntu
      command: terraform apply -auto-approve
      args:
        chdir: /home/ubuntu/terraform

    - name: Clean up Terraform files after apply
      file:
        path: /home/ubuntu/terraform
        state: absent
