FROM jenkins/jenkins:lts

USER root

# Install AWS CLI v2
RUN apt-get update && \
    apt-get install -y curl unzip sudo && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip" && \
    unzip /tmp/awscliv2.zip -d /tmp && \
    /tmp/aws/install && \
    rm -rf /tmp/aws /tmp/awscliv2.zip

# Optional: Add jenkins user to docker group
#RUN usermod -aG docker jenkins

USER jenkins
