- name: Install Docker and AWS CLI and  Run Jenkins
  hosts: jenkins
  become: true
  
  tasks:
    - name: Install prerequisite packages
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common", "python3-pip", "unzip"]
        state: present
        update_cache: yes
    - name: Download AWS CLI v2 installer
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      command: /tmp/aws/install

    - name: Verify AWS CLI version
      command: aws --version
      register: aws_cli_version

    - name: Show AWS CLI version
      debug:
        msg: "{{ aws_cli_version.stdout }}"

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Check Docker version
      command: docker --version
      register: docker_version_output


    - name: Debug Docker version
      debug:
        msg: "{{ docker_version_output.stdout }}"

    - name: Pull Jenkins Docker image
      shell: docker pull jenkins/jenkins
      become: yes

    - name: Run Jenkins container
      shell: |
        docker rm -f $(docker ps -aq)
        docker volume create jenkins_data
        docker run -d --name jenkins_container   -p 8080:8080   -v jenkins_data:/var/jenkins_home   -v /var/run/docker.sock:/var/run/docker.sock   -v /usr/bin/docker:/usr/bin/docker   --group-add $(stat -c "%g" /var/run/docker.sock)   jenkins/jenkins
      become: yes

    - name: Verify Jenkins is running
      shell: docker ps
      register: docker_ps_output

    - name: Display Docker ps output
      debug:
        msg: "{{ docker_ps_output.stdout_lines }}"
